# Generated by Django 2.0.13 on 2019-05-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day', '0003_trip_photo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='theme',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
