# Generated by Django 2.0.13 on 2019-05-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day', '0004_trip_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
