# Generated by Django 2.0.13 on 2019-05-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Day', '0005_auto_20190506_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.TextField(blank=True),
        ),
    ]
